services:
  - type: web
    name: casting-backend
    runtime: php
    repo: https://github.com/juste20/casting-back
    region: frankfurt
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan migrate --force
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://casting-backend.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_LEVEL
        value: warning
      - key: FRONTEND_URL
        value: https://casting.onrender.com
      - key: FEDAPAY_PUBLIC_KEY
        sync: false
      - key: FEDAPAY_SECRET_KEY
        sync: false
      - key: FEDAPAY_ENV
        value: sandbox
      - key: MAIL_MAILER
        value: log
